// <auto-generated />
using CorrectifExoEfCore.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorrectifExoEfCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231011093751_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CorrectifExoEfCore.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("MainActor")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Realisator")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Film", (string)null);

                    b.HasCheckConstraint("CK_ReleaseYear", "ReleaseYear > 1975");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            Realisator = "Georges Lucas",
                            ReleaseYear = 1977,
                            Title = "Star Wars : Un nouvel espoir"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            Realisator = "Georges Lucas",
                            ReleaseYear = 1980,
                            Title = "Star Wars : L'empire contre-attaque"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            Realisator = "Georges Lucas",
                            ReleaseYear = 1983,
                            Title = "Star Wars : Le retour du Jedi"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Société",
                            MainActor = "Charlie Hunnam",
                            Realisator = "Lexi Alexander",
                            ReleaseYear = 2005,
                            Title = "Hooligans"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            Realisator = "Peter Jackson",
                            ReleaseYear = 2001,
                            Title = "LOTR - La communauté de l'anneau"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            Realisator = "Peter Jackson",
                            ReleaseYear = 2002,
                            Title = "LOTR - Les deux tours"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            Realisator = "Peter Jackson",
                            ReleaseYear = 2003,
                            Title = "LOTR - Le retour du roi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
